services:
  db:
    image: mongo:latest
    container_name: unrowdy_db
    env_file:
      - backend/.env
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
  backend:
    tty: true
    container_name: unrowdy_backend
    build:
      context: ./backend
    env_file:
      - backend/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
  frontend:
    tty: true
    container_name: unrowdy_frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: true
volumes:
  db_data:
